param(
    [string]$ResourceGroup = "rg-kong-maf-demo",
    [string]$Location = "eastus2",
    [string]$FoundryResourceName = ("fdrykongmaf" + (Get-Date -Format "yyMMddHHmmss")),
    [string]$ProjectName = "kong-maf-demo",
    [string]$ModelName = "gpt-5.4-mini",
    [string]$ModelVersion = "2026-03-17",
    [string]$DeploymentName = "gpt-5-4-mini",
    [string]$DeploymentSku = "GlobalStandard",
    [int]$TpmCapacity = 10,
    [string]$OpenAIChatApiVersion = "2024-10-21"
)

$ErrorActionPreference = "Stop"
$rootDir = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $rootDir "agent/.env"
$templateFile = Join-Path $PSScriptRoot "foundry-account-project.bicep"

Write-Host "============================================"
Write-Host "  Kong + MAF Demo -- Azure Provisioning"
Write-Host "============================================"
Write-Host "Resource group:     $ResourceGroup"
Write-Host "Location:           $Location"
Write-Host "Foundry resource:   $FoundryResourceName"
Write-Host "Foundry project:    $ProjectName"
Write-Host "Model:              $ModelName"
Write-Host "Model version:      $ModelVersion"
Write-Host "Deployment name:    $DeploymentName"
Write-Host "Deployment SKU:     $DeploymentSku"
Write-Host "Capacity (k TPM):   $TpmCapacity"
Write-Host ""

Write-Host "[1/4] Creating resource group..."
az group create `
  --name $ResourceGroup `
  --location $Location `
  --output table

Write-Host "[2/4] Creating Foundry resource and project..."
$deploymentResult = az deployment group create `
  --resource-group $ResourceGroup `
  --name "kong-maf-foundry-bootstrap" `
  --template-file $templateFile `
  --parameters accountName=$FoundryResourceName projectName=$ProjectName location=$Location `
  --output json | ConvertFrom-Json

$projectEndpoint = $deploymentResult.properties.outputs.projectEndpoint.value

Write-Host "[3/4] Creating model deployment..."
az cognitiveservices account deployment create `
  --name $FoundryResourceName `
  --resource-group $ResourceGroup `
  --deployment-name $DeploymentName `
  --model-name $ModelName `
  --model-version $ModelVersion `
  --model-format OpenAI `
  --sku-name $DeploymentSku `
  --sku-capacity $TpmCapacity `
  --output table

Write-Host "[4/4] Writing agent configuration..."

@"
# Auto-generated by infra/provision.ps1
FOUNDRY_PROJECT_ENDPOINT=$projectEndpoint
FOUNDRY_MODEL=$DeploymentName
FOUNDRY_OPENAI_API_VERSION=$OpenAIChatApiVersion
AZURE_RESOURCE_GROUP=$ResourceGroup
FOUNDRY_RESOURCE_NAME=$FoundryResourceName
FOUNDRY_PROJECT_NAME=$ProjectName
FOUNDRY_MODEL_NAME=$ModelName
FOUNDRY_MODEL_VERSION=$ModelVersion
FOUNDRY_MODEL_DEPLOYMENT_NAME=$DeploymentName
"@ | Set-Content -Path $envFile -Encoding ascii

Write-Host ""
Write-Host "Provisioning complete."
Write-Host "Environment file written to $envFile"
