#!/usr/bin/env bash
set -euo pipefail

RESOURCE_GROUP="${RESOURCE_GROUP:-rg-kong-maf-demo}"
LOCATION="${LOCATION:-eastus}"
FOUNDRY_RESOURCE_NAME="${FOUNDRY_RESOURCE_NAME:-fdrykongmaf$(date +%s | tail -c 7)}"
PROJECT_NAME="${PROJECT_NAME:-kong-maf-demo}"
MODEL_NAME="${MODEL_NAME:-gpt-5.4-mini}"
MODEL_VERSION="${MODEL_VERSION:-2026-03-17}"
DEPLOYMENT_NAME="${DEPLOYMENT_NAME:-gpt-5-4-mini}"
DEPLOYMENT_SKU="${DEPLOYMENT_SKU:-GlobalStandard}"
TPM_CAPACITY="${TPM_CAPACITY:-10}"
OPENAI_CHAT_API_VERSION="${OPENAI_CHAT_API_VERSION:-2024-10-21}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
AGENT_ENV_FILE="${ROOT_DIR}/agent/.env"
TEMPLATE_FILE="${SCRIPT_DIR}/foundry-account-project.bicep"

echo "============================================"
echo "  Kong + MAF Demo -- Azure Provisioning"
echo "============================================"
echo "Resource group:     ${RESOURCE_GROUP}"
echo "Location:           ${LOCATION}"
echo "Foundry resource:   ${FOUNDRY_RESOURCE_NAME}"
echo "Foundry project:    ${PROJECT_NAME}"
echo "Model:              ${MODEL_NAME}"
echo "Model version:      ${MODEL_VERSION}"
echo "Deployment name:    ${DEPLOYMENT_NAME}"
echo "Deployment SKU:     ${DEPLOYMENT_SKU}"
echo "Capacity (k TPM):   ${TPM_CAPACITY}"
echo ""

echo "[1/4] Creating resource group..."
az group create \
  --name "${RESOURCE_GROUP}" \
  --location "${LOCATION}" \
  --output table

echo "[2/4] Creating Foundry resource and project..."
PROJECT_ENDPOINT="$(az deployment group create \
  --resource-group "${RESOURCE_GROUP}" \
  --name "kong-maf-foundry-bootstrap" \
  --template-file "${TEMPLATE_FILE}" \
  --parameters accountName="${FOUNDRY_RESOURCE_NAME}" projectName="${PROJECT_NAME}" location="${LOCATION}" \
  --query "properties.outputs.projectEndpoint.value" \
  --output tsv)"

echo "[3/4] Creating model deployment..."
az cognitiveservices account deployment create \
  --name "${FOUNDRY_RESOURCE_NAME}" \
  --resource-group "${RESOURCE_GROUP}" \
  --deployment-name "${DEPLOYMENT_NAME}" \
  --model-name "${MODEL_NAME}" \
  --model-version "${MODEL_VERSION}" \
  --model-format OpenAI \
  --sku-name "${DEPLOYMENT_SKU}" \
  --sku-capacity "${TPM_CAPACITY}" \
  --output table

echo "[4/4] Writing agent configuration..."

cat > "${AGENT_ENV_FILE}" <<EOF
# Auto-generated by infra/provision.sh
FOUNDRY_PROJECT_ENDPOINT=${PROJECT_ENDPOINT}
FOUNDRY_MODEL=${DEPLOYMENT_NAME}
FOUNDRY_OPENAI_API_VERSION=${OPENAI_CHAT_API_VERSION}
AZURE_RESOURCE_GROUP=${RESOURCE_GROUP}
FOUNDRY_RESOURCE_NAME=${FOUNDRY_RESOURCE_NAME}
FOUNDRY_PROJECT_NAME=${PROJECT_NAME}
FOUNDRY_MODEL_NAME=${MODEL_NAME}
FOUNDRY_MODEL_VERSION=${MODEL_VERSION}
FOUNDRY_MODEL_DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
EOF

echo ""
echo "Provisioning complete."
echo "Environment file written to ${AGENT_ENV_FILE}"
